# Generated by Django 5.0.6 on 2024-06-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QurilishTashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('hudud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maydoni', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qavat', models.IntegerField(default=1)),
                ('parking', models.BooleanField(default=True)),
                ('child_place', models.BooleanField(default=True)),
                ('elevator', models.BooleanField(default=True)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.hudud')),
                ('qurilish_tashkiloti', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.qurilishtashkiloti')),
            ],
        ),
    ]
